### ISSUE TITLE
Documenter graphiquement l'architecture logicielle

### ISSUE THREAD

**Issue by MattiSG** [betagouv/aides-jeunes-ops#27]
En tant qu'opérateur de Mes Aides,
Je dispose d'un [diagramme de typologie du système](http://myweb.lmu.edu/rnakatsu/diagrammaticreasoning/system%20topology.html),
Pour intervenir sur la pile logicielle et la définition Puppet

- - - -

- [ ] Puppet
- [ ] Nginx
- [ ] OpenFisca
- [ ] Mes Aides API
- [ ] Mes Aides UI
- [ ] CI
- [ ] Serveur de production
- [ ] GitHub

**Comment by guillett** [comment]
C'est disponible et en ligne. https://docs.google.com/presentation/d/127kz97HBMuw_6Tqhl2h7qbj1KgZXsB4Piqh2bNxhY-E/edit?usp=sharing :sweat_smile:
